import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Nav from '../components/Nav'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Micah M. Tinife | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Nav></Nav>
      </header>
      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
